package com.sonatel.yoonwi.utils

import java.io.File

import com.typesafe.config.ConfigFactory

object CustomConfig {

  /*SPARK WAREHOUSE PATH*/
  var SPARK_WAREHOUSE_PATH=""

  /*SPARK*/
  var MASTER=""
  var APPNAME=""

  /*SECTION*/
  var EXPERIMENT_SECTION_ID = 0
  var EXPERIMENT_SECTION_CRITICAL_VELOCITY = 0
  var EXPERIMENT_SECTION_FREE_VELOCITY = 0
  var EXPERIMENT_SECTION_MAXIMAL_CONCENTRATION = 0
  var EXPERIMENT_SECTION_CRITICAL_CONCENTRATION = 0

  /*MONGO*/
  var SLEEPING_INTERVAL = 0
  var  OUTPUT_URI = ""
  var COLLECTION = ""


  def load(inputPath : String) : Unit ={
    val myConfigFile = new File(inputPath)
    val configFile = ConfigFactory.parseFile(myConfigFile)

    SPARK_WAREHOUSE_PATH = configFile.getString("YOONWI.HDFS.SPARK_WAREHOUSE_PATH")
    MASTER = configFile.getString("YOONWI.SPARK.MASTER")
    APPNAME = configFile.getString("YOONWI.SPARK.APPNAME")
    EXPERIMENT_SECTION_ID = configFile.getInt("YOONWI.SECTION.EXPERIMENT_SECTION_ID")
    EXPERIMENT_SECTION_CRITICAL_VELOCITY = configFile.getInt("YOONWI.SECTION.EXPERIMENT_SECTION_CRITICAL_VELOCITY")
    EXPERIMENT_SECTION_FREE_VELOCITY = configFile.getInt("YOONWI.SECTION.EXPERIMENT_SECTION_FREE_VELOCITY")
    EXPERIMENT_SECTION_CRITICAL_CONCENTRATION = configFile.getInt("YOONWI.SECTION.EXPERIMENT_SECTION_CRITICAL_CONCENTRATION")
    EXPERIMENT_SECTION_MAXIMAL_CONCENTRATION = configFile.getInt("YOONWI.SECTION.EXPERIMENT_SECTION_MAXIMAL_CONCENTRATION")
    SLEEPING_INTERVAL = configFile.getInt("YOONWI.MONGO.SLEEPING_INTERVAL")
    OUTPUT_URI = configFile.getString("YOONWI.MONGO.OUTPUT_URI")
    COLLECTION = configFile.getString("YOONWI.MONGO.COLLECTION")

  }

}
